package com.yyaccp.dao;

import com.yyaccp.beans.pojo.ItripHotel;
import com.yyaccp.beans.pojo.ItripHotelWithBLOBs;

public interface ItripHotelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_hotel
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_hotel
     *
     * @mbggenerated
     */
    int insert(ItripHotelWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_hotel
     *
     * @mbggenerated
     */
    int insertSelective(ItripHotelWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_hotel
     *
     * @mbggenerated
     */
    ItripHotelWithBLOBs selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_hotel
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ItripHotelWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_hotel
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(ItripHotelWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_hotel
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ItripHotel record);
}