package com.yyaccp.dao;

import com.yyaccp.beans.pojo.ItripComment;

public interface ItripCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_comment
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_comment
     *
     * @mbggenerated
     */
    int insert(ItripComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_comment
     *
     * @mbggenerated
     */
    int insertSelective(ItripComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_comment
     *
     * @mbggenerated
     */
    ItripComment selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_comment
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ItripComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_comment
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(ItripComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_comment
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ItripComment record);
}