package com.yyaccp.dao;

import com.yyaccp.beans.pojo.ItripAreaDic;

public interface ItripAreaDicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_area_dic
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_area_dic
     *
     * @mbggenerated
     */
    int insert(ItripAreaDic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_area_dic
     *
     * @mbggenerated
     */
    int insertSelective(ItripAreaDic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_area_dic
     *
     * @mbggenerated
     */
    ItripAreaDic selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_area_dic
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ItripAreaDic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_area_dic
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ItripAreaDic record);
}