package com.yyaccp.dao;

import com.yyaccp.beans.pojo.ItripHotelOrder;

public interface ItripHotelOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_hotel_order
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_hotel_order
     *
     * @mbggenerated
     */
    int insert(ItripHotelOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_hotel_order
     *
     * @mbggenerated
     */
    int insertSelective(ItripHotelOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_hotel_order
     *
     * @mbggenerated
     */
    ItripHotelOrder selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_hotel_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ItripHotelOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_hotel_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(ItripHotelOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_hotel_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ItripHotelOrder record);
}