package com.yyaccp.dao;

import com.yyaccp.beans.pojo.ItripUser;

import java.util.List;
import java.util.Map;

public interface ItripUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_user
     *
     * @mbggenerated
     */
    int insert(ItripUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_user
     *
     * @mbggenerated
     */
    int insertSelective(ItripUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_user
     *
     * @mbggenerated
     */
    ItripUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ItripUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ItripUser record);

    List<ItripUser> selectByMap(Map<String, Object> map);
}