package com.yyaccp.dao;

import com.yyaccp.beans.pojo.ItripHotelTempStore;
import com.yyaccp.beans.vo.StoreVo;

import java.util.List;
import java.util.Map;

public interface ItripHotelTempStoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_hotel_temp_store
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_hotel_temp_store
     *
     * @mbggenerated
     */
    int insert(ItripHotelTempStore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_hotel_temp_store
     *
     * @mbggenerated
     */
    int insertSelective(ItripHotelTempStore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_hotel_temp_store
     *
     * @mbggenerated
     */
    ItripHotelTempStore selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_hotel_temp_store
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ItripHotelTempStore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_hotel_temp_store
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ItripHotelTempStore record);

    void flushStore(Map map);
    List<StoreVo> queryRoomStore(Map map);
}