package com.yyaccp.dao;

import com.yyaccp.beans.pojo.ItripUserLinkUser;

public interface ItripUserLinkUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_user_link_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_user_link_user
     *
     * @mbggenerated
     */
    int insert(ItripUserLinkUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_user_link_user
     *
     * @mbggenerated
     */
    int insertSelective(ItripUserLinkUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_user_link_user
     *
     * @mbggenerated
     */
    ItripUserLinkUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_user_link_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ItripUserLinkUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_user_link_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ItripUserLinkUser record);
}