package com.yyaccp.dao;

import com.yyaccp.beans.pojo.ItripHotelFeature;

public interface ItripHotelFeatureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_hotel_feature
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_hotel_feature
     *
     * @mbggenerated
     */
    int insert(ItripHotelFeature record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_hotel_feature
     *
     * @mbggenerated
     */
    int insertSelective(ItripHotelFeature record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_hotel_feature
     *
     * @mbggenerated
     */
    ItripHotelFeature selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_hotel_feature
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ItripHotelFeature record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_hotel_feature
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ItripHotelFeature record);
}