package com.yyaccp.dao;

import com.yyaccp.beans.pojo.ItripProductStore;

public interface ItripProductStoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_product_store
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_product_store
     *
     * @mbggenerated
     */
    int insert(ItripProductStore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_product_store
     *
     * @mbggenerated
     */
    int insertSelective(ItripProductStore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_product_store
     *
     * @mbggenerated
     */
    ItripProductStore selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_product_store
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ItripProductStore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itrip_product_store
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ItripProductStore record);
}