package com.yyaccp.beans.pojo;

import java.util.Date;

public class ItripUserLinkUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_user_link_user.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_user_link_user.linkUserName
     *
     * @mbggenerated
     */
    private String linkusername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_user_link_user.linkIdCard
     *
     * @mbggenerated
     */
    private String linkidcard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_user_link_user.linkPhone
     *
     * @mbggenerated
     */
    private String linkphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_user_link_user.userId
     *
     * @mbggenerated
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_user_link_user.creationDate
     *
     * @mbggenerated
     */
    private Date creationdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_user_link_user.createdBy
     *
     * @mbggenerated
     */
    private Long createdby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_user_link_user.modifyDate
     *
     * @mbggenerated
     */
    private Date modifydate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_user_link_user.modifiedBy
     *
     * @mbggenerated
     */
    private Long modifiedby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_user_link_user.linkIdCardType
     *
     * @mbggenerated
     */
    private Integer linkidcardtype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_user_link_user.id
     *
     * @return the value of itrip_user_link_user.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_user_link_user.id
     *
     * @param id the value for itrip_user_link_user.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_user_link_user.linkUserName
     *
     * @return the value of itrip_user_link_user.linkUserName
     *
     * @mbggenerated
     */
    public String getLinkusername() {
        return linkusername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_user_link_user.linkUserName
     *
     * @param linkusername the value for itrip_user_link_user.linkUserName
     *
     * @mbggenerated
     */
    public void setLinkusername(String linkusername) {
        this.linkusername = linkusername == null ? null : linkusername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_user_link_user.linkIdCard
     *
     * @return the value of itrip_user_link_user.linkIdCard
     *
     * @mbggenerated
     */
    public String getLinkidcard() {
        return linkidcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_user_link_user.linkIdCard
     *
     * @param linkidcard the value for itrip_user_link_user.linkIdCard
     *
     * @mbggenerated
     */
    public void setLinkidcard(String linkidcard) {
        this.linkidcard = linkidcard == null ? null : linkidcard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_user_link_user.linkPhone
     *
     * @return the value of itrip_user_link_user.linkPhone
     *
     * @mbggenerated
     */
    public String getLinkphone() {
        return linkphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_user_link_user.linkPhone
     *
     * @param linkphone the value for itrip_user_link_user.linkPhone
     *
     * @mbggenerated
     */
    public void setLinkphone(String linkphone) {
        this.linkphone = linkphone == null ? null : linkphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_user_link_user.userId
     *
     * @return the value of itrip_user_link_user.userId
     *
     * @mbggenerated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_user_link_user.userId
     *
     * @param userid the value for itrip_user_link_user.userId
     *
     * @mbggenerated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_user_link_user.creationDate
     *
     * @return the value of itrip_user_link_user.creationDate
     *
     * @mbggenerated
     */
    public Date getCreationdate() {
        return creationdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_user_link_user.creationDate
     *
     * @param creationdate the value for itrip_user_link_user.creationDate
     *
     * @mbggenerated
     */
    public void setCreationdate(Date creationdate) {
        this.creationdate = creationdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_user_link_user.createdBy
     *
     * @return the value of itrip_user_link_user.createdBy
     *
     * @mbggenerated
     */
    public Long getCreatedby() {
        return createdby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_user_link_user.createdBy
     *
     * @param createdby the value for itrip_user_link_user.createdBy
     *
     * @mbggenerated
     */
    public void setCreatedby(Long createdby) {
        this.createdby = createdby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_user_link_user.modifyDate
     *
     * @return the value of itrip_user_link_user.modifyDate
     *
     * @mbggenerated
     */
    public Date getModifydate() {
        return modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_user_link_user.modifyDate
     *
     * @param modifydate the value for itrip_user_link_user.modifyDate
     *
     * @mbggenerated
     */
    public void setModifydate(Date modifydate) {
        this.modifydate = modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_user_link_user.modifiedBy
     *
     * @return the value of itrip_user_link_user.modifiedBy
     *
     * @mbggenerated
     */
    public Long getModifiedby() {
        return modifiedby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_user_link_user.modifiedBy
     *
     * @param modifiedby the value for itrip_user_link_user.modifiedBy
     *
     * @mbggenerated
     */
    public void setModifiedby(Long modifiedby) {
        this.modifiedby = modifiedby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_user_link_user.linkIdCardType
     *
     * @return the value of itrip_user_link_user.linkIdCardType
     *
     * @mbggenerated
     */
    public Integer getLinkidcardtype() {
        return linkidcardtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_user_link_user.linkIdCardType
     *
     * @param linkidcardtype the value for itrip_user_link_user.linkIdCardType
     *
     * @mbggenerated
     */
    public void setLinkidcardtype(Integer linkidcardtype) {
        this.linkidcardtype = linkidcardtype;
    }
}