package com.yyaccp.beans.pojo;

import java.util.Date;

public class ItripHotelTempStore {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel_temp_store.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel_temp_store.hotelId
     *
     * @mbggenerated
     */
    private Integer hotelid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel_temp_store.roomId
     *
     * @mbggenerated
     */
    private Long roomid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel_temp_store.recordDate
     *
     * @mbggenerated
     */
    private Date recorddate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel_temp_store.store
     *
     * @mbggenerated
     */
    private Integer store;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel_temp_store.creationDate
     *
     * @mbggenerated
     */
    private Date creationdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel_temp_store.createdBy
     *
     * @mbggenerated
     */
    private Long createdby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel_temp_store.modifyDate
     *
     * @mbggenerated
     */
    private Date modifydate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel_temp_store.modifiedBy
     *
     * @mbggenerated
     */
    private Long modifiedby;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel_temp_store.id
     *
     * @return the value of itrip_hotel_temp_store.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel_temp_store.id
     *
     * @param id the value for itrip_hotel_temp_store.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel_temp_store.hotelId
     *
     * @return the value of itrip_hotel_temp_store.hotelId
     *
     * @mbggenerated
     */
    public Integer getHotelid() {
        return hotelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel_temp_store.hotelId
     *
     * @param hotelid the value for itrip_hotel_temp_store.hotelId
     *
     * @mbggenerated
     */
    public void setHotelid(Integer hotelid) {
        this.hotelid = hotelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel_temp_store.roomId
     *
     * @return the value of itrip_hotel_temp_store.roomId
     *
     * @mbggenerated
     */
    public Long getRoomid() {
        return roomid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel_temp_store.roomId
     *
     * @param roomid the value for itrip_hotel_temp_store.roomId
     *
     * @mbggenerated
     */
    public void setRoomid(Long roomid) {
        this.roomid = roomid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel_temp_store.recordDate
     *
     * @return the value of itrip_hotel_temp_store.recordDate
     *
     * @mbggenerated
     */
    public Date getRecorddate() {
        return recorddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel_temp_store.recordDate
     *
     * @param recorddate the value for itrip_hotel_temp_store.recordDate
     *
     * @mbggenerated
     */
    public void setRecorddate(Date recorddate) {
        this.recorddate = recorddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel_temp_store.store
     *
     * @return the value of itrip_hotel_temp_store.store
     *
     * @mbggenerated
     */
    public Integer getStore() {
        return store;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel_temp_store.store
     *
     * @param store the value for itrip_hotel_temp_store.store
     *
     * @mbggenerated
     */
    public void setStore(Integer store) {
        this.store = store;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel_temp_store.creationDate
     *
     * @return the value of itrip_hotel_temp_store.creationDate
     *
     * @mbggenerated
     */
    public Date getCreationdate() {
        return creationdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel_temp_store.creationDate
     *
     * @param creationdate the value for itrip_hotel_temp_store.creationDate
     *
     * @mbggenerated
     */
    public void setCreationdate(Date creationdate) {
        this.creationdate = creationdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel_temp_store.createdBy
     *
     * @return the value of itrip_hotel_temp_store.createdBy
     *
     * @mbggenerated
     */
    public Long getCreatedby() {
        return createdby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel_temp_store.createdBy
     *
     * @param createdby the value for itrip_hotel_temp_store.createdBy
     *
     * @mbggenerated
     */
    public void setCreatedby(Long createdby) {
        this.createdby = createdby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel_temp_store.modifyDate
     *
     * @return the value of itrip_hotel_temp_store.modifyDate
     *
     * @mbggenerated
     */
    public Date getModifydate() {
        return modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel_temp_store.modifyDate
     *
     * @param modifydate the value for itrip_hotel_temp_store.modifyDate
     *
     * @mbggenerated
     */
    public void setModifydate(Date modifydate) {
        this.modifydate = modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel_temp_store.modifiedBy
     *
     * @return the value of itrip_hotel_temp_store.modifiedBy
     *
     * @mbggenerated
     */
    public Long getModifiedby() {
        return modifiedby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel_temp_store.modifiedBy
     *
     * @param modifiedby the value for itrip_hotel_temp_store.modifiedBy
     *
     * @mbggenerated
     */
    public void setModifiedby(Long modifiedby) {
        this.modifiedby = modifiedby;
    }
}