package com.yyaccp.beans.pojo;

import java.util.Date;

public class ItripProductStore {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_product_store.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_product_store.productType
     *
     * @mbggenerated
     */
    private Integer producttype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_product_store.productId
     *
     * @mbggenerated
     */
    private Long productid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_product_store.store
     *
     * @mbggenerated
     */
    private Integer store;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_product_store.creationDate
     *
     * @mbggenerated
     */
    private Date creationdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_product_store.createdBy
     *
     * @mbggenerated
     */
    private Long createdby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_product_store.modifyDate
     *
     * @mbggenerated
     */
    private Date modifydate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_product_store.modifiedBy
     *
     * @mbggenerated
     */
    private Long modifiedby;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_product_store.id
     *
     * @return the value of itrip_product_store.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_product_store.id
     *
     * @param id the value for itrip_product_store.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_product_store.productType
     *
     * @return the value of itrip_product_store.productType
     *
     * @mbggenerated
     */
    public Integer getProducttype() {
        return producttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_product_store.productType
     *
     * @param producttype the value for itrip_product_store.productType
     *
     * @mbggenerated
     */
    public void setProducttype(Integer producttype) {
        this.producttype = producttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_product_store.productId
     *
     * @return the value of itrip_product_store.productId
     *
     * @mbggenerated
     */
    public Long getProductid() {
        return productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_product_store.productId
     *
     * @param productid the value for itrip_product_store.productId
     *
     * @mbggenerated
     */
    public void setProductid(Long productid) {
        this.productid = productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_product_store.store
     *
     * @return the value of itrip_product_store.store
     *
     * @mbggenerated
     */
    public Integer getStore() {
        return store;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_product_store.store
     *
     * @param store the value for itrip_product_store.store
     *
     * @mbggenerated
     */
    public void setStore(Integer store) {
        this.store = store;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_product_store.creationDate
     *
     * @return the value of itrip_product_store.creationDate
     *
     * @mbggenerated
     */
    public Date getCreationdate() {
        return creationdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_product_store.creationDate
     *
     * @param creationdate the value for itrip_product_store.creationDate
     *
     * @mbggenerated
     */
    public void setCreationdate(Date creationdate) {
        this.creationdate = creationdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_product_store.createdBy
     *
     * @return the value of itrip_product_store.createdBy
     *
     * @mbggenerated
     */
    public Long getCreatedby() {
        return createdby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_product_store.createdBy
     *
     * @param createdby the value for itrip_product_store.createdBy
     *
     * @mbggenerated
     */
    public void setCreatedby(Long createdby) {
        this.createdby = createdby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_product_store.modifyDate
     *
     * @return the value of itrip_product_store.modifyDate
     *
     * @mbggenerated
     */
    public Date getModifydate() {
        return modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_product_store.modifyDate
     *
     * @param modifydate the value for itrip_product_store.modifyDate
     *
     * @mbggenerated
     */
    public void setModifydate(Date modifydate) {
        this.modifydate = modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_product_store.modifiedBy
     *
     * @return the value of itrip_product_store.modifiedBy
     *
     * @mbggenerated
     */
    public Long getModifiedby() {
        return modifiedby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_product_store.modifiedBy
     *
     * @param modifiedby the value for itrip_product_store.modifiedBy
     *
     * @mbggenerated
     */
    public void setModifiedby(Long modifiedby) {
        this.modifiedby = modifiedby;
    }
}