package com.yyaccp.beans.pojo;

import java.util.Date;

public class ItripComment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_comment.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_comment.hotelId
     *
     * @mbggenerated
     */
    private Long hotelid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_comment.productId
     *
     * @mbggenerated
     */
    private Long productid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_comment.orderId
     *
     * @mbggenerated
     */
    private Long orderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_comment.productType
     *
     * @mbggenerated
     */
    private Integer producttype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_comment.userId
     *
     * @mbggenerated
     */
    private Long userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_comment.isHavingImg
     *
     * @mbggenerated
     */
    private Integer ishavingimg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_comment.positionScore
     *
     * @mbggenerated
     */
    private Integer positionscore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_comment.facilitiesScore
     *
     * @mbggenerated
     */
    private Integer facilitiesscore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_comment.serviceScore
     *
     * @mbggenerated
     */
    private Integer servicescore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_comment.hygieneScore
     *
     * @mbggenerated
     */
    private Integer hygienescore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_comment.score
     *
     * @mbggenerated
     */
    private Integer score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_comment.tripMode
     *
     * @mbggenerated
     */
    private Long tripmode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_comment.isOk
     *
     * @mbggenerated
     */
    private Integer isok;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_comment.creationDate
     *
     * @mbggenerated
     */
    private Date creationdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_comment.createdBy
     *
     * @mbggenerated
     */
    private Long createdby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_comment.modifyDate
     *
     * @mbggenerated
     */
    private Date modifydate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_comment.modifiedBy
     *
     * @mbggenerated
     */
    private Long modifiedby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_comment.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_comment.id
     *
     * @return the value of itrip_comment.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_comment.id
     *
     * @param id the value for itrip_comment.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_comment.hotelId
     *
     * @return the value of itrip_comment.hotelId
     *
     * @mbggenerated
     */
    public Long getHotelid() {
        return hotelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_comment.hotelId
     *
     * @param hotelid the value for itrip_comment.hotelId
     *
     * @mbggenerated
     */
    public void setHotelid(Long hotelid) {
        this.hotelid = hotelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_comment.productId
     *
     * @return the value of itrip_comment.productId
     *
     * @mbggenerated
     */
    public Long getProductid() {
        return productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_comment.productId
     *
     * @param productid the value for itrip_comment.productId
     *
     * @mbggenerated
     */
    public void setProductid(Long productid) {
        this.productid = productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_comment.orderId
     *
     * @return the value of itrip_comment.orderId
     *
     * @mbggenerated
     */
    public Long getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_comment.orderId
     *
     * @param orderid the value for itrip_comment.orderId
     *
     * @mbggenerated
     */
    public void setOrderid(Long orderid) {
        this.orderid = orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_comment.productType
     *
     * @return the value of itrip_comment.productType
     *
     * @mbggenerated
     */
    public Integer getProducttype() {
        return producttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_comment.productType
     *
     * @param producttype the value for itrip_comment.productType
     *
     * @mbggenerated
     */
    public void setProducttype(Integer producttype) {
        this.producttype = producttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_comment.userId
     *
     * @return the value of itrip_comment.userId
     *
     * @mbggenerated
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_comment.userId
     *
     * @param userid the value for itrip_comment.userId
     *
     * @mbggenerated
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_comment.isHavingImg
     *
     * @return the value of itrip_comment.isHavingImg
     *
     * @mbggenerated
     */
    public Integer getIshavingimg() {
        return ishavingimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_comment.isHavingImg
     *
     * @param ishavingimg the value for itrip_comment.isHavingImg
     *
     * @mbggenerated
     */
    public void setIshavingimg(Integer ishavingimg) {
        this.ishavingimg = ishavingimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_comment.positionScore
     *
     * @return the value of itrip_comment.positionScore
     *
     * @mbggenerated
     */
    public Integer getPositionscore() {
        return positionscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_comment.positionScore
     *
     * @param positionscore the value for itrip_comment.positionScore
     *
     * @mbggenerated
     */
    public void setPositionscore(Integer positionscore) {
        this.positionscore = positionscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_comment.facilitiesScore
     *
     * @return the value of itrip_comment.facilitiesScore
     *
     * @mbggenerated
     */
    public Integer getFacilitiesscore() {
        return facilitiesscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_comment.facilitiesScore
     *
     * @param facilitiesscore the value for itrip_comment.facilitiesScore
     *
     * @mbggenerated
     */
    public void setFacilitiesscore(Integer facilitiesscore) {
        this.facilitiesscore = facilitiesscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_comment.serviceScore
     *
     * @return the value of itrip_comment.serviceScore
     *
     * @mbggenerated
     */
    public Integer getServicescore() {
        return servicescore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_comment.serviceScore
     *
     * @param servicescore the value for itrip_comment.serviceScore
     *
     * @mbggenerated
     */
    public void setServicescore(Integer servicescore) {
        this.servicescore = servicescore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_comment.hygieneScore
     *
     * @return the value of itrip_comment.hygieneScore
     *
     * @mbggenerated
     */
    public Integer getHygienescore() {
        return hygienescore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_comment.hygieneScore
     *
     * @param hygienescore the value for itrip_comment.hygieneScore
     *
     * @mbggenerated
     */
    public void setHygienescore(Integer hygienescore) {
        this.hygienescore = hygienescore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_comment.score
     *
     * @return the value of itrip_comment.score
     *
     * @mbggenerated
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_comment.score
     *
     * @param score the value for itrip_comment.score
     *
     * @mbggenerated
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_comment.tripMode
     *
     * @return the value of itrip_comment.tripMode
     *
     * @mbggenerated
     */
    public Long getTripmode() {
        return tripmode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_comment.tripMode
     *
     * @param tripmode the value for itrip_comment.tripMode
     *
     * @mbggenerated
     */
    public void setTripmode(Long tripmode) {
        this.tripmode = tripmode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_comment.isOk
     *
     * @return the value of itrip_comment.isOk
     *
     * @mbggenerated
     */
    public Integer getIsok() {
        return isok;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_comment.isOk
     *
     * @param isok the value for itrip_comment.isOk
     *
     * @mbggenerated
     */
    public void setIsok(Integer isok) {
        this.isok = isok;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_comment.creationDate
     *
     * @return the value of itrip_comment.creationDate
     *
     * @mbggenerated
     */
    public Date getCreationdate() {
        return creationdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_comment.creationDate
     *
     * @param creationdate the value for itrip_comment.creationDate
     *
     * @mbggenerated
     */
    public void setCreationdate(Date creationdate) {
        this.creationdate = creationdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_comment.createdBy
     *
     * @return the value of itrip_comment.createdBy
     *
     * @mbggenerated
     */
    public Long getCreatedby() {
        return createdby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_comment.createdBy
     *
     * @param createdby the value for itrip_comment.createdBy
     *
     * @mbggenerated
     */
    public void setCreatedby(Long createdby) {
        this.createdby = createdby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_comment.modifyDate
     *
     * @return the value of itrip_comment.modifyDate
     *
     * @mbggenerated
     */
    public Date getModifydate() {
        return modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_comment.modifyDate
     *
     * @param modifydate the value for itrip_comment.modifyDate
     *
     * @mbggenerated
     */
    public void setModifydate(Date modifydate) {
        this.modifydate = modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_comment.modifiedBy
     *
     * @return the value of itrip_comment.modifiedBy
     *
     * @mbggenerated
     */
    public Long getModifiedby() {
        return modifiedby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_comment.modifiedBy
     *
     * @param modifiedby the value for itrip_comment.modifiedBy
     *
     * @mbggenerated
     */
    public void setModifiedby(Long modifiedby) {
        this.modifiedby = modifiedby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_comment.content
     *
     * @return the value of itrip_comment.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_comment.content
     *
     * @param content the value for itrip_comment.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}