package com.yyaccp.beans.pojo;

public class ItripHotelWithBLOBs extends ItripHotel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel.details
     *
     * @mbggenerated
     */
    private String details;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel.facilities
     *
     * @mbggenerated
     */
    private String facilities;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel.hotelPolicy
     *
     * @mbggenerated
     */
    private String hotelpolicy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel.details
     *
     * @return the value of itrip_hotel.details
     *
     * @mbggenerated
     */
    public String getDetails() {
        return details;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel.details
     *
     * @param details the value for itrip_hotel.details
     *
     * @mbggenerated
     */
    public void setDetails(String details) {
        this.details = details == null ? null : details.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel.facilities
     *
     * @return the value of itrip_hotel.facilities
     *
     * @mbggenerated
     */
    public String getFacilities() {
        return facilities;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel.facilities
     *
     * @param facilities the value for itrip_hotel.facilities
     *
     * @mbggenerated
     */
    public void setFacilities(String facilities) {
        this.facilities = facilities == null ? null : facilities.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel.hotelPolicy
     *
     * @return the value of itrip_hotel.hotelPolicy
     *
     * @mbggenerated
     */
    public String getHotelpolicy() {
        return hotelpolicy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel.hotelPolicy
     *
     * @param hotelpolicy the value for itrip_hotel.hotelPolicy
     *
     * @mbggenerated
     */
    public void setHotelpolicy(String hotelpolicy) {
        this.hotelpolicy = hotelpolicy == null ? null : hotelpolicy.trim();
    }
}