package com.yyaccp.beans.pojo;

import java.math.BigDecimal;
import java.util.Date;

public class ItripHotelRoom {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel_room.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel_room.hotelId
     *
     * @mbggenerated
     */
    private Long hotelid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel_room.roomTitle
     *
     * @mbggenerated
     */
    private String roomtitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel_room.roomPrice
     *
     * @mbggenerated
     */
    private BigDecimal roomprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel_room.roomBedTypeId
     *
     * @mbggenerated
     */
    private Long roombedtypeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel_room.isHavingBreakfast
     *
     * @mbggenerated
     */
    private Integer ishavingbreakfast;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel_room.payType
     *
     * @mbggenerated
     */
    private Integer paytype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel_room.satisfaction
     *
     * @mbggenerated
     */
    private Long satisfaction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel_room.isBook
     *
     * @mbggenerated
     */
    private Integer isbook;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel_room.isCancel
     *
     * @mbggenerated
     */
    private Integer iscancel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel_room.isTimelyResponse
     *
     * @mbggenerated
     */
    private Integer istimelyresponse;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel_room.creationDate
     *
     * @mbggenerated
     */
    private Date creationdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel_room.createdBy
     *
     * @mbggenerated
     */
    private Long createdby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel_room.modifyDate
     *
     * @mbggenerated
     */
    private Date modifydate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel_room.modifiedBy
     *
     * @mbggenerated
     */
    private Long modifiedby;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel_room.id
     *
     * @return the value of itrip_hotel_room.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel_room.id
     *
     * @param id the value for itrip_hotel_room.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel_room.hotelId
     *
     * @return the value of itrip_hotel_room.hotelId
     *
     * @mbggenerated
     */
    public Long getHotelid() {
        return hotelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel_room.hotelId
     *
     * @param hotelid the value for itrip_hotel_room.hotelId
     *
     * @mbggenerated
     */
    public void setHotelid(Long hotelid) {
        this.hotelid = hotelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel_room.roomTitle
     *
     * @return the value of itrip_hotel_room.roomTitle
     *
     * @mbggenerated
     */
    public String getRoomtitle() {
        return roomtitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel_room.roomTitle
     *
     * @param roomtitle the value for itrip_hotel_room.roomTitle
     *
     * @mbggenerated
     */
    public void setRoomtitle(String roomtitle) {
        this.roomtitle = roomtitle == null ? null : roomtitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel_room.roomPrice
     *
     * @return the value of itrip_hotel_room.roomPrice
     *
     * @mbggenerated
     */
    public BigDecimal getRoomprice() {
        return roomprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel_room.roomPrice
     *
     * @param roomprice the value for itrip_hotel_room.roomPrice
     *
     * @mbggenerated
     */
    public void setRoomprice(BigDecimal roomprice) {
        this.roomprice = roomprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel_room.roomBedTypeId
     *
     * @return the value of itrip_hotel_room.roomBedTypeId
     *
     * @mbggenerated
     */
    public Long getRoombedtypeid() {
        return roombedtypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel_room.roomBedTypeId
     *
     * @param roombedtypeid the value for itrip_hotel_room.roomBedTypeId
     *
     * @mbggenerated
     */
    public void setRoombedtypeid(Long roombedtypeid) {
        this.roombedtypeid = roombedtypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel_room.isHavingBreakfast
     *
     * @return the value of itrip_hotel_room.isHavingBreakfast
     *
     * @mbggenerated
     */
    public Integer getIshavingbreakfast() {
        return ishavingbreakfast;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel_room.isHavingBreakfast
     *
     * @param ishavingbreakfast the value for itrip_hotel_room.isHavingBreakfast
     *
     * @mbggenerated
     */
    public void setIshavingbreakfast(Integer ishavingbreakfast) {
        this.ishavingbreakfast = ishavingbreakfast;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel_room.payType
     *
     * @return the value of itrip_hotel_room.payType
     *
     * @mbggenerated
     */
    public Integer getPaytype() {
        return paytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel_room.payType
     *
     * @param paytype the value for itrip_hotel_room.payType
     *
     * @mbggenerated
     */
    public void setPaytype(Integer paytype) {
        this.paytype = paytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel_room.satisfaction
     *
     * @return the value of itrip_hotel_room.satisfaction
     *
     * @mbggenerated
     */
    public Long getSatisfaction() {
        return satisfaction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel_room.satisfaction
     *
     * @param satisfaction the value for itrip_hotel_room.satisfaction
     *
     * @mbggenerated
     */
    public void setSatisfaction(Long satisfaction) {
        this.satisfaction = satisfaction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel_room.isBook
     *
     * @return the value of itrip_hotel_room.isBook
     *
     * @mbggenerated
     */
    public Integer getIsbook() {
        return isbook;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel_room.isBook
     *
     * @param isbook the value for itrip_hotel_room.isBook
     *
     * @mbggenerated
     */
    public void setIsbook(Integer isbook) {
        this.isbook = isbook;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel_room.isCancel
     *
     * @return the value of itrip_hotel_room.isCancel
     *
     * @mbggenerated
     */
    public Integer getIscancel() {
        return iscancel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel_room.isCancel
     *
     * @param iscancel the value for itrip_hotel_room.isCancel
     *
     * @mbggenerated
     */
    public void setIscancel(Integer iscancel) {
        this.iscancel = iscancel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel_room.isTimelyResponse
     *
     * @return the value of itrip_hotel_room.isTimelyResponse
     *
     * @mbggenerated
     */
    public Integer getIstimelyresponse() {
        return istimelyresponse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel_room.isTimelyResponse
     *
     * @param istimelyresponse the value for itrip_hotel_room.isTimelyResponse
     *
     * @mbggenerated
     */
    public void setIstimelyresponse(Integer istimelyresponse) {
        this.istimelyresponse = istimelyresponse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel_room.creationDate
     *
     * @return the value of itrip_hotel_room.creationDate
     *
     * @mbggenerated
     */
    public Date getCreationdate() {
        return creationdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel_room.creationDate
     *
     * @param creationdate the value for itrip_hotel_room.creationDate
     *
     * @mbggenerated
     */
    public void setCreationdate(Date creationdate) {
        this.creationdate = creationdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel_room.createdBy
     *
     * @return the value of itrip_hotel_room.createdBy
     *
     * @mbggenerated
     */
    public Long getCreatedby() {
        return createdby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel_room.createdBy
     *
     * @param createdby the value for itrip_hotel_room.createdBy
     *
     * @mbggenerated
     */
    public void setCreatedby(Long createdby) {
        this.createdby = createdby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel_room.modifyDate
     *
     * @return the value of itrip_hotel_room.modifyDate
     *
     * @mbggenerated
     */
    public Date getModifydate() {
        return modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel_room.modifyDate
     *
     * @param modifydate the value for itrip_hotel_room.modifyDate
     *
     * @mbggenerated
     */
    public void setModifydate(Date modifydate) {
        this.modifydate = modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel_room.modifiedBy
     *
     * @return the value of itrip_hotel_room.modifiedBy
     *
     * @mbggenerated
     */
    public Long getModifiedby() {
        return modifiedby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel_room.modifiedBy
     *
     * @param modifiedby the value for itrip_hotel_room.modifiedBy
     *
     * @mbggenerated
     */
    public void setModifiedby(Long modifiedby) {
        this.modifiedby = modifiedby;
    }
}