package com.yyaccp.beans.pojo;

public class ItripTradeEnds {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_trade_ends.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_trade_ends.orderNo
     *
     * @mbggenerated
     */
    private String orderno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_trade_ends.flag
     *
     * @mbggenerated
     */
    private Boolean flag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_trade_ends.id
     *
     * @return the value of itrip_trade_ends.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_trade_ends.id
     *
     * @param id the value for itrip_trade_ends.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_trade_ends.orderNo
     *
     * @return the value of itrip_trade_ends.orderNo
     *
     * @mbggenerated
     */
    public String getOrderno() {
        return orderno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_trade_ends.orderNo
     *
     * @param orderno the value for itrip_trade_ends.orderNo
     *
     * @mbggenerated
     */
    public void setOrderno(String orderno) {
        this.orderno = orderno == null ? null : orderno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_trade_ends.flag
     *
     * @return the value of itrip_trade_ends.flag
     *
     * @mbggenerated
     */
    public Boolean getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_trade_ends.flag
     *
     * @param flag the value for itrip_trade_ends.flag
     *
     * @mbggenerated
     */
    public void setFlag(Boolean flag) {
        this.flag = flag;
    }
}