package com.yyaccp.beans.pojo;

import java.util.Date;

public class ItripHotelFeature {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel_feature.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel_feature.hotelId
     *
     * @mbggenerated
     */
    private Long hotelid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel_feature.featureId
     *
     * @mbggenerated
     */
    private Long featureid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel_feature.creationDate
     *
     * @mbggenerated
     */
    private Date creationdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel_feature.createdBy
     *
     * @mbggenerated
     */
    private Long createdby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel_feature.modifyDate
     *
     * @mbggenerated
     */
    private Date modifydate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel_feature.modifiedBy
     *
     * @mbggenerated
     */
    private Long modifiedby;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel_feature.id
     *
     * @return the value of itrip_hotel_feature.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel_feature.id
     *
     * @param id the value for itrip_hotel_feature.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel_feature.hotelId
     *
     * @return the value of itrip_hotel_feature.hotelId
     *
     * @mbggenerated
     */
    public Long getHotelid() {
        return hotelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel_feature.hotelId
     *
     * @param hotelid the value for itrip_hotel_feature.hotelId
     *
     * @mbggenerated
     */
    public void setHotelid(Long hotelid) {
        this.hotelid = hotelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel_feature.featureId
     *
     * @return the value of itrip_hotel_feature.featureId
     *
     * @mbggenerated
     */
    public Long getFeatureid() {
        return featureid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel_feature.featureId
     *
     * @param featureid the value for itrip_hotel_feature.featureId
     *
     * @mbggenerated
     */
    public void setFeatureid(Long featureid) {
        this.featureid = featureid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel_feature.creationDate
     *
     * @return the value of itrip_hotel_feature.creationDate
     *
     * @mbggenerated
     */
    public Date getCreationdate() {
        return creationdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel_feature.creationDate
     *
     * @param creationdate the value for itrip_hotel_feature.creationDate
     *
     * @mbggenerated
     */
    public void setCreationdate(Date creationdate) {
        this.creationdate = creationdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel_feature.createdBy
     *
     * @return the value of itrip_hotel_feature.createdBy
     *
     * @mbggenerated
     */
    public Long getCreatedby() {
        return createdby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel_feature.createdBy
     *
     * @param createdby the value for itrip_hotel_feature.createdBy
     *
     * @mbggenerated
     */
    public void setCreatedby(Long createdby) {
        this.createdby = createdby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel_feature.modifyDate
     *
     * @return the value of itrip_hotel_feature.modifyDate
     *
     * @mbggenerated
     */
    public Date getModifydate() {
        return modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel_feature.modifyDate
     *
     * @param modifydate the value for itrip_hotel_feature.modifyDate
     *
     * @mbggenerated
     */
    public void setModifydate(Date modifydate) {
        this.modifydate = modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel_feature.modifiedBy
     *
     * @return the value of itrip_hotel_feature.modifiedBy
     *
     * @mbggenerated
     */
    public Long getModifiedby() {
        return modifiedby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel_feature.modifiedBy
     *
     * @param modifiedby the value for itrip_hotel_feature.modifiedBy
     *
     * @mbggenerated
     */
    public void setModifiedby(Long modifiedby) {
        this.modifiedby = modifiedby;
    }
}