package com.yyaccp.beans.pojo;

import java.util.Date;

public class ItripUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_user.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_user.userCode
     *
     * @mbggenerated
     */
    private String usercode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_user.userPassword
     *
     * @mbggenerated
     */
    private String userpassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_user.userType
     *
     * @mbggenerated
     */
    private Integer usertype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_user.flatID
     *
     * @mbggenerated
     */
    private Long flatid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_user.userName
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_user.weChat
     *
     * @mbggenerated
     */
    private String wechat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_user.QQ
     *
     * @mbggenerated
     */
    private String qq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_user.weibo
     *
     * @mbggenerated
     */
    private String weibo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_user.baidu
     *
     * @mbggenerated
     */
    private String baidu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_user.creationDate
     *
     * @mbggenerated
     */
    private Date creationdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_user.createdBy
     *
     * @mbggenerated
     */
    private Long createdby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_user.modifyDate
     *
     * @mbggenerated
     */
    private Date modifydate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_user.modifiedBy
     *
     * @mbggenerated
     */
    private Long modifiedby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_user.activated
     *
     * @mbggenerated
     */
    private Integer activated;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_user.id
     *
     * @return the value of itrip_user.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_user.id
     *
     * @param id the value for itrip_user.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_user.userCode
     *
     * @return the value of itrip_user.userCode
     *
     * @mbggenerated
     */
    public String getUsercode() {
        return usercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_user.userCode
     *
     * @param usercode the value for itrip_user.userCode
     *
     * @mbggenerated
     */
    public void setUsercode(String usercode) {
        this.usercode = usercode == null ? null : usercode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_user.userPassword
     *
     * @return the value of itrip_user.userPassword
     *
     * @mbggenerated
     */
    public String getUserpassword() {
        return userpassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_user.userPassword
     *
     * @param userpassword the value for itrip_user.userPassword
     *
     * @mbggenerated
     */
    public void setUserpassword(String userpassword) {
        this.userpassword = userpassword == null ? null : userpassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_user.userType
     *
     * @return the value of itrip_user.userType
     *
     * @mbggenerated
     */
    public Integer getUsertype() {
        return usertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_user.userType
     *
     * @param usertype the value for itrip_user.userType
     *
     * @mbggenerated
     */
    public void setUsertype(Integer usertype) {
        this.usertype = usertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_user.flatID
     *
     * @return the value of itrip_user.flatID
     *
     * @mbggenerated
     */
    public Long getFlatid() {
        return flatid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_user.flatID
     *
     * @param flatid the value for itrip_user.flatID
     *
     * @mbggenerated
     */
    public void setFlatid(Long flatid) {
        this.flatid = flatid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_user.userName
     *
     * @return the value of itrip_user.userName
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_user.userName
     *
     * @param username the value for itrip_user.userName
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_user.weChat
     *
     * @return the value of itrip_user.weChat
     *
     * @mbggenerated
     */
    public String getWechat() {
        return wechat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_user.weChat
     *
     * @param wechat the value for itrip_user.weChat
     *
     * @mbggenerated
     */
    public void setWechat(String wechat) {
        this.wechat = wechat == null ? null : wechat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_user.QQ
     *
     * @return the value of itrip_user.QQ
     *
     * @mbggenerated
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_user.QQ
     *
     * @param qq the value for itrip_user.QQ
     *
     * @mbggenerated
     */
    public void setQq(String qq) {
        this.qq = qq == null ? null : qq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_user.weibo
     *
     * @return the value of itrip_user.weibo
     *
     * @mbggenerated
     */
    public String getWeibo() {
        return weibo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_user.weibo
     *
     * @param weibo the value for itrip_user.weibo
     *
     * @mbggenerated
     */
    public void setWeibo(String weibo) {
        this.weibo = weibo == null ? null : weibo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_user.baidu
     *
     * @return the value of itrip_user.baidu
     *
     * @mbggenerated
     */
    public String getBaidu() {
        return baidu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_user.baidu
     *
     * @param baidu the value for itrip_user.baidu
     *
     * @mbggenerated
     */
    public void setBaidu(String baidu) {
        this.baidu = baidu == null ? null : baidu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_user.creationDate
     *
     * @return the value of itrip_user.creationDate
     *
     * @mbggenerated
     */
    public Date getCreationdate() {
        return creationdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_user.creationDate
     *
     * @param creationdate the value for itrip_user.creationDate
     *
     * @mbggenerated
     */
    public void setCreationdate(Date creationdate) {
        this.creationdate = creationdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_user.createdBy
     *
     * @return the value of itrip_user.createdBy
     *
     * @mbggenerated
     */
    public Long getCreatedby() {
        return createdby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_user.createdBy
     *
     * @param createdby the value for itrip_user.createdBy
     *
     * @mbggenerated
     */
    public void setCreatedby(Long createdby) {
        this.createdby = createdby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_user.modifyDate
     *
     * @return the value of itrip_user.modifyDate
     *
     * @mbggenerated
     */
    public Date getModifydate() {
        return modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_user.modifyDate
     *
     * @param modifydate the value for itrip_user.modifyDate
     *
     * @mbggenerated
     */
    public void setModifydate(Date modifydate) {
        this.modifydate = modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_user.modifiedBy
     *
     * @return the value of itrip_user.modifiedBy
     *
     * @mbggenerated
     */
    public Long getModifiedby() {
        return modifiedby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_user.modifiedBy
     *
     * @param modifiedby the value for itrip_user.modifiedBy
     *
     * @mbggenerated
     */
    public void setModifiedby(Long modifiedby) {
        this.modifiedby = modifiedby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_user.activated
     *
     * @return the value of itrip_user.activated
     *
     * @mbggenerated
     */
    public Integer getActivated() {
        return activated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_user.activated
     *
     * @param activated the value for itrip_user.activated
     *
     * @mbggenerated
     */
    public void setActivated(Integer activated) {
        this.activated = activated;
    }
}