package com.yyaccp.beans.pojo;

import java.util.Date;

public class ItripOrderLinkUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_order_link_user.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_order_link_user.orderId
     *
     * @mbggenerated
     */
    private Long orderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_order_link_user.linkUserId
     *
     * @mbggenerated
     */
    private Long linkuserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_order_link_user.linkUserName
     *
     * @mbggenerated
     */
    private String linkusername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_order_link_user.creationDate
     *
     * @mbggenerated
     */
    private Date creationdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_order_link_user.createdBy
     *
     * @mbggenerated
     */
    private Long createdby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_order_link_user.modifyDate
     *
     * @mbggenerated
     */
    private Date modifydate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_order_link_user.modifiedBy
     *
     * @mbggenerated
     */
    private Long modifiedby;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_order_link_user.id
     *
     * @return the value of itrip_order_link_user.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_order_link_user.id
     *
     * @param id the value for itrip_order_link_user.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_order_link_user.orderId
     *
     * @return the value of itrip_order_link_user.orderId
     *
     * @mbggenerated
     */
    public Long getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_order_link_user.orderId
     *
     * @param orderid the value for itrip_order_link_user.orderId
     *
     * @mbggenerated
     */
    public void setOrderid(Long orderid) {
        this.orderid = orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_order_link_user.linkUserId
     *
     * @return the value of itrip_order_link_user.linkUserId
     *
     * @mbggenerated
     */
    public Long getLinkuserid() {
        return linkuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_order_link_user.linkUserId
     *
     * @param linkuserid the value for itrip_order_link_user.linkUserId
     *
     * @mbggenerated
     */
    public void setLinkuserid(Long linkuserid) {
        this.linkuserid = linkuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_order_link_user.linkUserName
     *
     * @return the value of itrip_order_link_user.linkUserName
     *
     * @mbggenerated
     */
    public String getLinkusername() {
        return linkusername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_order_link_user.linkUserName
     *
     * @param linkusername the value for itrip_order_link_user.linkUserName
     *
     * @mbggenerated
     */
    public void setLinkusername(String linkusername) {
        this.linkusername = linkusername == null ? null : linkusername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_order_link_user.creationDate
     *
     * @return the value of itrip_order_link_user.creationDate
     *
     * @mbggenerated
     */
    public Date getCreationdate() {
        return creationdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_order_link_user.creationDate
     *
     * @param creationdate the value for itrip_order_link_user.creationDate
     *
     * @mbggenerated
     */
    public void setCreationdate(Date creationdate) {
        this.creationdate = creationdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_order_link_user.createdBy
     *
     * @return the value of itrip_order_link_user.createdBy
     *
     * @mbggenerated
     */
    public Long getCreatedby() {
        return createdby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_order_link_user.createdBy
     *
     * @param createdby the value for itrip_order_link_user.createdBy
     *
     * @mbggenerated
     */
    public void setCreatedby(Long createdby) {
        this.createdby = createdby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_order_link_user.modifyDate
     *
     * @return the value of itrip_order_link_user.modifyDate
     *
     * @mbggenerated
     */
    public Date getModifydate() {
        return modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_order_link_user.modifyDate
     *
     * @param modifydate the value for itrip_order_link_user.modifyDate
     *
     * @mbggenerated
     */
    public void setModifydate(Date modifydate) {
        this.modifydate = modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_order_link_user.modifiedBy
     *
     * @return the value of itrip_order_link_user.modifiedBy
     *
     * @mbggenerated
     */
    public Long getModifiedby() {
        return modifiedby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_order_link_user.modifiedBy
     *
     * @param modifiedby the value for itrip_order_link_user.modifiedBy
     *
     * @mbggenerated
     */
    public void setModifiedby(Long modifiedby) {
        this.modifiedby = modifiedby;
    }
}