package com.yyaccp.beans.pojo;

import java.util.Date;

public class ItripHotel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel.hotelName
     *
     * @mbggenerated
     */
    private String hotelname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel.countryId
     *
     * @mbggenerated
     */
    private Long countryid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel.provinceId
     *
     * @mbggenerated
     */
    private Long provinceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel.cityId
     *
     * @mbggenerated
     */
    private Long cityid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel.hotelType
     *
     * @mbggenerated
     */
    private Integer hoteltype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel.hotelLevel
     *
     * @mbggenerated
     */
    private Integer hotellevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel.isGroupPurchase
     *
     * @mbggenerated
     */
    private Integer isgrouppurchase;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel.redundantCityName
     *
     * @mbggenerated
     */
    private String redundantcityname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel.redundantProvinceName
     *
     * @mbggenerated
     */
    private String redundantprovincename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel.redundantCountryName
     *
     * @mbggenerated
     */
    private String redundantcountryname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel.redundantHotelStore
     *
     * @mbggenerated
     */
    private Integer redundanthotelstore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel.creationDate
     *
     * @mbggenerated
     */
    private Date creationdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel.createdBy
     *
     * @mbggenerated
     */
    private Long createdby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel.modifyDate
     *
     * @mbggenerated
     */
    private Date modifydate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itrip_hotel.modifiedBy
     *
     * @mbggenerated
     */
    private Long modifiedby;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel.id
     *
     * @return the value of itrip_hotel.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel.id
     *
     * @param id the value for itrip_hotel.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel.hotelName
     *
     * @return the value of itrip_hotel.hotelName
     *
     * @mbggenerated
     */
    public String getHotelname() {
        return hotelname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel.hotelName
     *
     * @param hotelname the value for itrip_hotel.hotelName
     *
     * @mbggenerated
     */
    public void setHotelname(String hotelname) {
        this.hotelname = hotelname == null ? null : hotelname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel.countryId
     *
     * @return the value of itrip_hotel.countryId
     *
     * @mbggenerated
     */
    public Long getCountryid() {
        return countryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel.countryId
     *
     * @param countryid the value for itrip_hotel.countryId
     *
     * @mbggenerated
     */
    public void setCountryid(Long countryid) {
        this.countryid = countryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel.provinceId
     *
     * @return the value of itrip_hotel.provinceId
     *
     * @mbggenerated
     */
    public Long getProvinceid() {
        return provinceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel.provinceId
     *
     * @param provinceid the value for itrip_hotel.provinceId
     *
     * @mbggenerated
     */
    public void setProvinceid(Long provinceid) {
        this.provinceid = provinceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel.cityId
     *
     * @return the value of itrip_hotel.cityId
     *
     * @mbggenerated
     */
    public Long getCityid() {
        return cityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel.cityId
     *
     * @param cityid the value for itrip_hotel.cityId
     *
     * @mbggenerated
     */
    public void setCityid(Long cityid) {
        this.cityid = cityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel.address
     *
     * @return the value of itrip_hotel.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel.address
     *
     * @param address the value for itrip_hotel.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel.hotelType
     *
     * @return the value of itrip_hotel.hotelType
     *
     * @mbggenerated
     */
    public Integer getHoteltype() {
        return hoteltype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel.hotelType
     *
     * @param hoteltype the value for itrip_hotel.hotelType
     *
     * @mbggenerated
     */
    public void setHoteltype(Integer hoteltype) {
        this.hoteltype = hoteltype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel.hotelLevel
     *
     * @return the value of itrip_hotel.hotelLevel
     *
     * @mbggenerated
     */
    public Integer getHotellevel() {
        return hotellevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel.hotelLevel
     *
     * @param hotellevel the value for itrip_hotel.hotelLevel
     *
     * @mbggenerated
     */
    public void setHotellevel(Integer hotellevel) {
        this.hotellevel = hotellevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel.isGroupPurchase
     *
     * @return the value of itrip_hotel.isGroupPurchase
     *
     * @mbggenerated
     */
    public Integer getIsgrouppurchase() {
        return isgrouppurchase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel.isGroupPurchase
     *
     * @param isgrouppurchase the value for itrip_hotel.isGroupPurchase
     *
     * @mbggenerated
     */
    public void setIsgrouppurchase(Integer isgrouppurchase) {
        this.isgrouppurchase = isgrouppurchase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel.redundantCityName
     *
     * @return the value of itrip_hotel.redundantCityName
     *
     * @mbggenerated
     */
    public String getRedundantcityname() {
        return redundantcityname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel.redundantCityName
     *
     * @param redundantcityname the value for itrip_hotel.redundantCityName
     *
     * @mbggenerated
     */
    public void setRedundantcityname(String redundantcityname) {
        this.redundantcityname = redundantcityname == null ? null : redundantcityname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel.redundantProvinceName
     *
     * @return the value of itrip_hotel.redundantProvinceName
     *
     * @mbggenerated
     */
    public String getRedundantprovincename() {
        return redundantprovincename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel.redundantProvinceName
     *
     * @param redundantprovincename the value for itrip_hotel.redundantProvinceName
     *
     * @mbggenerated
     */
    public void setRedundantprovincename(String redundantprovincename) {
        this.redundantprovincename = redundantprovincename == null ? null : redundantprovincename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel.redundantCountryName
     *
     * @return the value of itrip_hotel.redundantCountryName
     *
     * @mbggenerated
     */
    public String getRedundantcountryname() {
        return redundantcountryname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel.redundantCountryName
     *
     * @param redundantcountryname the value for itrip_hotel.redundantCountryName
     *
     * @mbggenerated
     */
    public void setRedundantcountryname(String redundantcountryname) {
        this.redundantcountryname = redundantcountryname == null ? null : redundantcountryname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel.redundantHotelStore
     *
     * @return the value of itrip_hotel.redundantHotelStore
     *
     * @mbggenerated
     */
    public Integer getRedundanthotelstore() {
        return redundanthotelstore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel.redundantHotelStore
     *
     * @param redundanthotelstore the value for itrip_hotel.redundantHotelStore
     *
     * @mbggenerated
     */
    public void setRedundanthotelstore(Integer redundanthotelstore) {
        this.redundanthotelstore = redundanthotelstore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel.creationDate
     *
     * @return the value of itrip_hotel.creationDate
     *
     * @mbggenerated
     */
    public Date getCreationdate() {
        return creationdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel.creationDate
     *
     * @param creationdate the value for itrip_hotel.creationDate
     *
     * @mbggenerated
     */
    public void setCreationdate(Date creationdate) {
        this.creationdate = creationdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel.createdBy
     *
     * @return the value of itrip_hotel.createdBy
     *
     * @mbggenerated
     */
    public Long getCreatedby() {
        return createdby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel.createdBy
     *
     * @param createdby the value for itrip_hotel.createdBy
     *
     * @mbggenerated
     */
    public void setCreatedby(Long createdby) {
        this.createdby = createdby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel.modifyDate
     *
     * @return the value of itrip_hotel.modifyDate
     *
     * @mbggenerated
     */
    public Date getModifydate() {
        return modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel.modifyDate
     *
     * @param modifydate the value for itrip_hotel.modifyDate
     *
     * @mbggenerated
     */
    public void setModifydate(Date modifydate) {
        this.modifydate = modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itrip_hotel.modifiedBy
     *
     * @return the value of itrip_hotel.modifiedBy
     *
     * @mbggenerated
     */
    public Long getModifiedby() {
        return modifiedby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itrip_hotel.modifiedBy
     *
     * @param modifiedby the value for itrip_hotel.modifiedBy
     *
     * @mbggenerated
     */
    public void setModifiedby(Long modifiedby) {
        this.modifiedby = modifiedby;
    }
}